name:                easytensor-vulkan
version:             2.0.1.0
github:              "achirkin/easytensor/easytensor-vulkan"
license:             BSD3
author:              "Artem Chirkin"
maintainer:          "achirkin@users.noreply.github.com"
copyright:           "Copyright: (c) 2019 Artem Chirkin"
synopsis:            Use easytensor with vulkan-api.
category:            math, geometry, vulkan, bsd3, graphics, library, opengl
description:
    Use easytensor DataFrame types with vulkan-api.
    This package provides an orphan instance of PrimBytes for Vulkan structures,
    so they can be used as elements of DataFrames.
    In addition, it provides a few helper functions for working with array-like
    structures.

ghc-options:
  - -Wall
  - -Wcompat
  - -Wtabs
  - -Wmonomorphism-restriction
  - -Wmissing-local-signatures
  - -Wmissing-home-modules
  - -Widentities
  - -Wredundant-constraints

dependencies:
  - base >= 4.11 && < 5
  - dimensions >= 2 && < 3
  - easytensor >= 2.0.1.0 && < 3
  - vulkan-api >= 1.3.0.0 && < 2

library:
  source-dirs: src
  other-modules: []
