resolver:
  name: snaphot-ghc-8.2.1
  location: snaphot-ghc-8.2.1.yaml
compiler: ghc-8.2.0.20170404
compiler-check: match-exact
setup-info:
 ghc:
  linux64:
   8.2.0.20170404:
    url: https://downloads.haskell.org/~ghc/8.2.1-rc1/ghc-8.2.0.20170404-x86_64-deb8-linux.tar.xz


packages:
  - "."

extra-deps: []
flags: {}
