name:                dimensions
version:             2.1.1.0
github:              "achirkin/easytensor/dimensions"
license:             BSD3
author:              "Artem Chirkin"
maintainer:          "achirkin@users.noreply.github.com"
copyright:           "Copyright: (c) 2019 Artem Chirkin"
synopsis:            Safe type-level dimensionality for multidimensional data.
category:            math, geometry
description:         Safe type-level dimensionality for multidimensional data.
                     Please see the README on GitHub at <https://github.com/achirkin/easytensor#readme>

flags:

  unsafeindices:
    description:
      Disable bound checks on Idx and Idxs types.
    default: false
    manual: true

ghc-options:
  - -Wall
  - -Wcompat
  - -Wtabs
  - -Wmissing-local-signatures
  - -Wmissing-home-modules
  - -Widentities

custom-setup:
  dependencies:
  - base
  - Cabal

dependencies:
  - base >= 4.10 && < 5
  - constraints-deriving >= 1.1.1.0 && < 2

library:
  source-dirs: src
  other-modules:
  - Data.Type.List.Families
  - Data.Type.List.Classes
  - Data.Type.List.Internal
  when:
  - condition: flag(unsafeindices)
    cpp-options: -DUNSAFE_INDICES

tests:

  dimensions-test:
    main:                Spec.hs
    source-dirs:         test
    dependencies:
    - base
    - Cabal
    - QuickCheck
    - dimensions
